version: "3" 
services:
  crash_docker:
    build: .
    container_name: crash_docker
    hostname: crash_docker
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - ./crash-logs-docker/:/opt/
    #command: tail -f /dev/null
    command: ["python3", "/opt/app.py", "${LOG_NAME1}", "${IP1}", "${PORT1}"]