version: "3" 
services:
  crash_docker:
    build: .
    container_name: crash_docker
    hostname: crash_docker
    network_mode: "host"
    volumes:
      - ./logs/:/opt/logs
      - ./ser2net.conf:/etc/ser2net.conf:rw
    devices:
      - ${COM_PATH1}:/dev/ttyUSB0
    command: ["/opt/logs/start.sh", "${MODE}", "${LOG_NAME1}"]