version: "3" 
services:
  crash_docker:
    build: .
    container_name: crash_docker
    hostname: crash_docker
    network_mode: "host"
    volumes:
      - ./crash-logs-docker/:/opt/
    devices:
      - ${COM_PATH1}:/dev/ttyUSB0
    command: ["/opt/start.sh", "${LOG_NAME1}"]