version: "3" 
services:
  crash_docker:
    build: .
    container_name: crash_docker
    hostname: crash_docker
    volumes:
      - ./:/opt/logs
    devices:
      - /dev/ttyUSB${COM_NUM}:/dev/ttyUSB0
#      - /dev/ttyUSB${COM_NUM2}:/dev/ttyUSB1
#      - /dev/ttyUSB2:/dev/ttyUSB2
    command: ["/opt/logs/start.sh", "${LOG_NAME}"]
#      - "/opt/logs/start.sh ${LOG_NAME}"